ClientTravelr/Models/ApiHelper.cs
using System.Threading.Tasks;
using RestSharp;

namespace ClientTravelr.Models
{
    class ApiHelper
    {
      public static async Task<string> GetAll()
      {
        RestClient client = new RestClient("http://localhost:5004/api");
        RestRequest request = new RestRequest($"destinations", Method.GET);
        var response = await client.ExecuteTaskAsync(request);
        return response.Content;
      }

      public static async Task<string> Get(int id)
      {
        RestClient client = new RestClient("http://localhost:5004/api");
        RestRequest request = new RestRequest($"destinations/{id}", Method.GET);
        var response = await client.ExecuteTaskAsync(request);
        return response.Content;
      }

      public static async Task Post(string newDestination)
      {
        RestClient client = new RestClient("http://localhost:5004/api");
        RestRequest request = new RestRequest($"destinations", Method.POST);
        request.AddHeader("Content-Type", "application/json");
        request.AddJsonBody(newDestination);
        var response = await client.ExecuteTaskAsync(request);
      }

      public static async Task Put(int id, string newDestination)
      {
        RestClient client = new RestClient("http://localhost:5004/api");
        RestRequest request = new RestRequest($"destinations/{id}", Method.PUT); 
        request.AddHeader("Content-Type", "application/json");
        request.AddJsonBody(newDestination);
        var response = await client.ExecuteTaskAsync(request);
      }

      public static async Task Delete(int id)
      {
        RestClient client = new RestClient("http://localhost:5004/api");
        RestRequest request = new RestRequest($"destinations/{id}", Method.DELETE);
        request.AddHeader("Content-Type", "application/json");
        var response = await client.ExecuteTaskAsync(request);
      }
    }
}

ClientTravelr/Models/Destination.cs
using System;
using System.Collections.Generic;

using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ClientTravelr.Models
{
  public class Destination
  {
    public int DestinationId { get; set; }
    public string CityName { get; set; }
    public string Country { get; set; }
    public string Review { get; set; }
    public int Rating { get; set; }

    public static List<Destination> GetDestinations()
    {
      var apiCallTask = ApiHelper.GetAll();
      var result = apiCallTask.Result;

      JArray jsonResponse = JsonConvert.DeserializeObject<JArray>(result);
      List<Destination> destinationList = JsonConvert.DeserializeObject<List<Destination>>(jsonResponse.ToString());

      return destinationList;
    }

    public static Destination GetDetails(int id)
    {
      var apiCallTask = ApiHelper.Get(id);
      var result = apiCallTask.Result;

      JObject jsonResponse = JsonConvert.DeserializeObject<JObject>(result);
      Destination destination = JsonConvert.DeserializeObject<Destination>(jsonResponse.ToString());

      return destination;
    }

    public static void Post(Destination destination)
    {
      string jsonDestination = JsonConvert.SerializeObject(destination);
      var apiCallTask = ApiHelper.Post(jsonDestination);
    }

    public static void Put(Destination destination)
    {
      string jsonDestination = JsonConvert.SerializeObject(destination);
      var apiCallTask = ApiHelper.Put(destination.DestinationId, jsonDestination);
    }

    public static void Delete(int id)
    {
      var apiCallTask = ApiHelper.Delete(id);
    }
  }
}

ClientTravelr/Models/ErrorViewModel.cs
using System;

namespace ClientTravelr.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ClientTravelr/Controllers/DestinationsController.cs
using ClientTravelr.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq;

namespace ClientTravelr.Controllers
{
    public class DestinationsController: Controller
    {
      public IActionResult Index()
      {
        var allDestinations = Destination.GetDestinations();
        return View(allDestinations);
      }

      public IActionResult Details(int id)
      {
        var thisDestination = Destination.GetDetails(id);
        return View(thisDestination);
      }

      public IActionResult Create()
      {
        return View();
      }

      [HttpPost]
      public IActionResult Create(Destination destination)
      {
        Destination.Post(destination);
        var timer = Task.Delay(100); //DO NOT KEEP THIS HERE
        timer.Wait();
        return RedirectToAction("Index");
      }

      public IActionResult Edit(int id)
      {
        var thisDestination = Destination.GetDetails(id);
        return View(thisDestination);
      }

      [HttpPost]
      public IActionResult Edit(Destination destination)
      {
        Destination.Put(destination);
        return RedirectToAction("Details", new { id = destination.DestinationId });
      }

      [HttpPost]
      public IActionResult Delete(int id)
      {
        Destination.Delete(id);
        return RedirectToAction("Index");
      }
    }
}

ClientTravelr/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ClientTravelr.Models;

namespace ClientTravelr.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ClientTravelr/Views/Destinations/Create.cshtml
@{
  Layout = "_Layout";
}

@model ClientTravelr.Models.Destination;

<h1>Add a new destinations</h1>
<hr>
@using (Html.BeginForm())
{
  <div class="form-group">
    @Html.Label("City")
    @Html.TextBoxFor(model => model.CityName, new { @class = "form-control" })
  </div>
  <div class="form-group">
    @Html.Label("Country")
    @Html.TextBoxFor(model => model.Country, new { @class = "form-control"})
  </div>
  <div class="form-group">
    @Html.Label("Review")
    @Html.TextAreaFor(model => model.Review, new { @class = "form-control"})
  </div>
  <div class="form-group">
    @Html.Label("Rating")
    @Html.TextBoxFor(model => model.Rating, new { @class = "form-control"})
  </div>
  <input type="submit" value="Add" class="btn btn-outline-secondary" />
}

ClientTravelr/Views/Destinations/Details.cshtml
@{
  Layout="_Layout";
}

@model ClientTravelr.Models.Destination;

<h1 class="display-2">@Model.CityName</h1>
<hr>
<div class="row">
  <div class="col-sm-6">
    <h3>Country: @Model.Country</h3>
    <h3>Rating: @Model.Rating </h3>
  </div>
  <div class="col-sm-6">
    <h3>Review:</h3>
    <p>@Model.Review</p>
  </div>
</div>
@Html.ActionLink("Edit Review", "Edit", new { id = Model.DestinationId })

ClientTravelr/Views/Destinations/Edit.cshtml
@{
  Layout = "_Layout";
}

@model ClientTravelr.Models.Destination;

<h1>Edit @Model.CityName</h1>
<hr>
@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.DestinationId)
  <div class="form-group">
    @Html.Label("City")
    @Html.TextBoxFor(model => model.CityName, new { @class = "form-control" })
  </div>
  <div class="form-group">
    @Html.Label("Country")
    @Html.TextBoxFor(model => model.Country, new { @class = "form-control"})
  </div>
  <div class="form-group">
    @Html.Label("Review")
    @Html.TextAreaFor(model => model.Review, new { @class = "form-control"})
  </div>
  <div class="form-group">
    @Html.Label("Rating")
    @Html.TextBoxFor(model => model.Rating, new { @class = "form-control"})
  </div>
  <input type="submit" value="Add" class="btn btn-outline-secondary" />
}

ClientTravelr/Views/Destinations/Index.cshtml
@{
  Layout="_Layout";
}

@* @model ClientTravelr.Models.Destination; *@

<h1 class="display-2">All Destinations</h1>

  @foreach(Destination destination in Model)
  {
    <div class="card">
      <div class="card-header">
        <a href="/Destinations/Details/@(destination.DestinationId)" class="display-3">@destination.CityName</a>
      </div>
      <div class="card-body">
        <ul>
          <li>Country: @destination.Country</li>
          <li>Rating: @destination.Rating</li>
        </ul>
      </div>
      <div class="card-footer">
      @using (@Html.BeginForm("Delete", "Destinations"))
      {
        @Html.Hidden("id", @destination.DestinationId)
        <input class="btn btn-outline-danger" type="submit" value="Delete">
      }
      </div>
    </div>
    <br>
  }

ClientTravelr/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ClientTravelr/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClientTravelr</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ClientTravelr</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ClientTravelr - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>